######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 1 23:46:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gpgproc.h klinebufferedprocess.h kprocess.h kprocess_p.h
SOURCES += gpgproc.cpp klinebufferedprocess.cpp kprocess.cpp
