######################################################################
# Automatically generated by qmake (2.01a) Fr. Mär 29 03:44:24 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += version.cpp
